### ISSUE TITLE
Horizontal behavior is not supported !

### ISSUE THREAD

**Issue by RahulSDeshpande** [kapil93/CircularLayoutManager#13]
Kapil bro !!
Amazing work !!

I was checking out your lib thoroughly, but I found that this lib doesn't support horizontal scrolling behavior.
I tried to extend the CircularLayoutManager class & implementing the setOrientation methods & various orientation related methods & member variables, but I get stuck in the middle as there are a lot of things to implement.

Thanks in advance !!
Cheers man !!

👍

**Comment by kapil93** [comment]
Thanks Rahul :)

Instead of extending the class I encourage you to fork and modify the project itself, it would be much simpler.

Overriding "scrollHorizontallyBy" method and pasting all the code from "scrollVerticallyBy" into it should be a good start. Also, don't forget to override "canScrollHorizontally" and return true.

Cheers !!

**Comment by RahulSDeshpande** [comment]
Oh, yea !!
Thanks a lot !!

Have already been doing that, will raise a PR if I get it done :)

Thanks, Kapil !!

👍

**Comment by kapil93** [comment]
Same as [issue #12](https://github.com/kapil93/Circular-Layout-Manager/issues/12)
